name: Build Dist Apps

on:
  push:
    tags:
      - '*'

jobs:
  build-dist-apps:
    if: github.repository == 'coralsundy/mahjong-player' || github.ref_type == 'tag'
    strategy:
      matrix:
        node_version:
          - '20.x'
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2022
          - macos-13
          - macos-14 # arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install node ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install rustup
        uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4
        with:
          toolchain: 'stable'

      - name: Install dependencies linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y \
            libgtk-3-dev \
            libglib2.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            libwebkit2gtk-4.1-dev \
            build-essential \
            pkg-config \
            curl

      - name: Build app ${{ matrix.os }}
        shell: bash
        run: |
          npm install
          npx tauri build
          cd src-tauri/target/release/bundle
          mkdir artifacts
          OS=${{ matrix.os }}
          if [[ "$OS" = *"ubuntu"* ]]; then
            PKG_RPM=`find . -name '*.rpm'`
            PKG_DEB=`find . -name '*.deb'`
            PKG_APPIMAGE=`find . -name '*.AppImage'`
            mv -v $PKG_RPM $PKG_DEB $PKG_APPIMAGE artifacts/
          elif [[ "$OS" = *"windows"* ]]; then
            PKG_MSI=`find . -name '*.msi'`
            PKG_EXE=`find . -name '*.exe'`
            mv -v $PKG_MSI $PKG_EXE artifacts/
          elif [[ "$OS" = *"macos"* ]]; then
            cd dmg
            PKG_DMG=`find . -name '*.dmg'`
            mv -v $PKG_DMG ../artifacts/
          fi

      - name: Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: artifacts-${{ matrix.os }}
          path: src-tauri/target/release/bundle/artifacts/*

  release-dist-artifacts:
    if: github.repository == 'coralsundy/mahjong-player' || github.ref_type == 'tag'
    runs-on: ubuntu-24.04
    needs: build-dist-apps
    permissions:
      contents: write

    steps:
      - name: Retrieve artifacts ubuntu-24.04
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: artifacts-ubuntu-24.04
          path: artifacts

      - name: Retrieve artifacts ubuntu-24.04-arm64
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: artifacts-ubuntu-24.04-arm
          path: artifacts

      - name: Retrieve artifacts windows-2022
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: artifacts-windows-2022
          path: artifacts

      - name: Retrieve artifacts macos-13
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: artifacts-macos-13
          path: artifacts

      - name: Retrieve artifacts macos-14 arm64
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: artifacts-macos-14
          path: artifacts

      - name: Verify all artifacts
        run: ls artifacts/

      - name: Release all Artifacts
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: artifacts/*
          generate_release_notes: true
          make_latest: true
          token: ${{ secrets.GITHUB_TOKEN }}
